// Smoke test for the patched official workspace client bundle
// (lib/client.js, generated by lib/build.mjs): executes it in Node with a
// minimal DOM + services stub so syntax/typo/apply errors are caught before
// the browser loads it. Rendering happens inside the slot framework, so apply
// only needs locale/slots/workspaces/sessions stubs.
import { createRequire } from "node:module"
import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import { homedir } from "node:os"

const profileRequire = createRequire(join(homedir(), ".dsh", "profiles", "web", "package.json"))
const React = profileRequire("react")

let factory
const fakeWindow = {
  __ModuleLoader__: {
    load: ({ id, factory: f }) => {
      if (id !== "dsh-worktree-panel") throw new Error("unexpected bundle id: " + id)
      factory = f
    },
  },
}

const code = readFileSync(join(dirname(fileURLToPath(import.meta.url)), "..", "lib", "client.js"), "utf8")
// The bundle touches document only inside __wtpEnsureCss (called from a
// component hook) and the CSS module injector, which is guarded by
// `typeof document !== "undefined"`; render paths are not exercised here.
new Function("window", code)(fakeWindow)

if (!factory) throw new Error("bundle did not register a factory")

const primitivesStub = new Proxy(
  {},
  {
    get: (target, prop) => {
      if (prop === Symbol.toStringTag) return "Module"
      // Components reference icons/primitives lazily at render time only.
      return (...args) => (typeof args[0] === "string" ? args[0] : "stub")
    },
  },
)

const mod = factory((name) => {
  if (name === "react") return React
  if (name === "react/jsx-runtime") {
    return { jsx: React.createElement, jsxs: React.createElement, Fragment: React.Fragment }
  }
  if (name === "@deepseek-ai/dsh-client-runtime/client") {
    return { defineStore: (spec) => ({ ...spec }) }
  }
  if (name === "@deepseek-ai/dsh-client-ui-primitives") return primitivesStub
  throw new Error("unexpected require: " + name)
})

if (typeof mod.apply !== "function") throw new Error("client bundle exports no apply")
if (!Array.isArray(mod.inject)) throw new Error("client bundle exports no inject list")

const registrations = []
const ctx = {
  locale: { register: () => {} },
  sessions: {
    search: async () => ({ ok: true, value: { items: [] } }),
    searchResultLimit: 50,
    binding: () => undefined,
    fork: async () => "child",
    open: () => {},
  },
  workspaces: {
    startSession: () => {},
    rename: async () => {},
    delete: async () => {},
    insertBefore: async () => {},
    archiveSession: async () => {},
    insertSessionBefore: async () => {},
    create: async () => ({}),
  },
  slots: {
    entries: () => [],
    subscribe: () => () => {},
    inject: (name, cb) => {
      registrations.push({ name, registered: cb() })
    },
    register: (opts, Component) => ({ opts, Component }),
  },
  effect: (fn) => {
    const dispose = fn()
    return () => {
      try {
        dispose?.()
      } catch {
        /* ignore */
      }
    }
  },
}

mod.apply(ctx) // official apply registers effects/slots via ctx; returns undefined by design

const slotNames = registrations.map((r) => r.name).join(",")
if (!slotNames.includes("sidebar.workspaces")) throw new Error("sidebar.workspaces slot not registered")
if (!slotNames.includes("conversation.hero.workspace")) throw new Error("hero workspace slot not registered")

console.log(
  "client smoke test OK: patched official bundle factory ran, apply registered slots [" + slotNames + "]",
)
